services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    container_name: keycloak
    restart: always
    command: start-dev   #  Development mode (no TLS required)
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - keycloak_data:/opt/keycloak/data

  openbao:
    image: openbao/openbao:latest
    container_name: openbao
    restart: always
    command: server -config=/etc/openbao/config.hcl
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - ./openbao/config.hcl:/etc/openbao/config.hcl
      - ./openbao/data:/opt/openbao/data

volumes:
  postgres_data:
  keycloak_data:
  openbao_data:
